name: 5etranslated - Fork Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    # Run only if it's not the main repository
    if: ${{ github.repository != '5etoolstranslated/deploy_template' }}
    steps:
      - uses: actions/checkout@main
        with:
          ref: "main"
          token: ${{ secrets.PERSONAL_TOKEN }} # Must be added to the repo in Settings > Secrets and variables > Actions

      - name: Merge latest deploy_template main repo
        run: |
          git checkout main
          git remote add upstream https://github.com/5etoolstranslated/deploy_template
          git fetch upstream
          git reset --hard upstream/main
          git config user.name "GH Actions Automation"
          git config user.email "<>"
          git push --force
